### ISSUE TITLE
Auth Question

### ISSUE THREAD

**Issue by jdscolam** [appdotnet/api-spec#108] opened 2012-08-20 03:21 UTC
Two questions here.  First of all, what is the guidance on user tokens.  Maybe I'm missing something here, but after you have a user token from the user authorizing your app, is it necessary to cache those tokens on the user's machine or phone so they don't have to re-auth your app?

Secondly, is there an easier way to achieve the user token if you are using a client-side app?  I am writing API wrappers for the .NET platform, and having to open a new browser outside of the process, then open a website for authorization, then redirect to some externally served page makes testing out the API extremely difficult.  What is the guidence here?

Thanks in advance for your advice and input.

-Jon

**Comment by jdscolam** [comment] 2012-08-20 03:32
A follow-up to this question is, would it make sense for there to be a clearing house for apps that aren't web-based?  For example, if my user has authenticated my app, then the redirect URL points to an clearing house server that stores all of the authentication tokens for a given app (or all apps) so that way a client, after making a request, can check to see if that request was authorized, and retrieve the user's authentication token from the clearing house.  Just some suggestions/ideas, as I am really struggling to get this authentication flow going.

**Comment by abraham** [comment] 2012-08-20 03:52
1) All API requests require an access_token. So if you don't want users to re-auth every time they start your app the access_token must be cached somehow.

2) Currently the only auth flow supported is the web/browser flow. You can follow issue 45 for updates on alternative auth flows.

3) I'm not sure what use a clearing house server would have as it couldn't hand out access_tokens freely and would require some sort of token itself. Might as well skip that step and just store the access_token locally.

**Comment by jdscolam** [comment] 2012-08-20 03:59
Thanks for the feedback @abraham, it really helps!

For the clearing-house, it provides a way for an app that doesn't have a redirectUri (e.g. a console application or library) to retrieve the user token by waiting for the token to appear, and then timing out the access request after a given amount of time (if the user doesn't authorize the request).

That being said, I'll have to go check out issue 45, and give it a +1.

**Comment by mthurman** [comment] 2012-08-23 21:31
Closing this issue since the problems seem to have been addressed and the remaining issue is a duplicate of #45.

**Closed as completed by mthurman** 2012-08-23 21:31 UTC
