### ISSUE TITLE
Should allow self-reposts

### ISSUE THREAD

**Issue by beccadax** [appdotnet/api-spec#209] opened 2012-10-10 00:19 UTC
On Twitter, a user can retweet one of his own tweets. This seems useless at first, but it actually has an important use: you can retweet a reply, and then it will become visible to your followers, even if they don't follow the user mentioned in the reply.

App.net currently returns a 400 error when you try to repost one of your own posts. I believe it should instead follow Twitter's lead and make a repost that your followers will see.

**Comment by abraham** [comment] 2012-10-10 00:23
What Twitter UIs let you retweet your own tweet?

**Comment by kosso** [comment] 2012-10-10 00:30
Just my 2c, but I can't stand self-retweeters. ;D

You can "re-quote" yourself though. Just not a 'native' one.

**Comment by jmergy** [comment] 2012-10-10 00:43
Agree. Re-quote or reference to the original post URL makes the most sense. Tweetbot does quote over at the Birdhouse.

**Comment by DaveWoodCom** [comment] 2012-10-10 01:39
There's another very good reason (at least on Twitter) to retweet your own tweet.  Since users don't see a duplicate of a tweet if it's retweeted, a retweet of your own tweet prevents people from seeing it twice, but still lets new followers and others see it if they missed the first one.  Timezones etc.

**Comment by abraham** [comment] 2012-10-10 04:27
How is it that people retweet themselves on Twitter. I'm unaware of any way for that actually being possible. You could always quote yourself (classic RT) of course but that isn't what you guys have been talking about.

**Comment by DaveWoodCom** [comment] 2012-10-10 05:37
Interesting.  I know I have retweeted myself in the past, but you're right, it seems hard (impossible?) to do now. Checked Twitter (iPhone/Mac/Web), Tweetbot (iPhone/Mac), Twitterrific (iPhone/Mac).  None of them allow you to natively retweet yourself anymore.

**Comment by berg** [comment] 2012-10-23 21:17
Agree about re-quote or referencing original post. Unfortunately, I believe self-reposts are incompatible with our implementation.

**Closed as completed by berg** 2012-10-23 21:17 UTC
