### ISSUE TITLE
Geolocation Annotation

### ISSUE THREAD

**Issue by matthewp** [appdotnet/api-spec#163] opened 2012-09-03 22:30 UTC
Since it hasn't been proposed yet, and seems rather obvious, I'll break the ice here.  I'm proposing geolocation defined as such:

``` json
{
  "type": "net.app.core.geolocation",
  "value": {
    "coordinates": [38.288596,-85.581897]
  }
}
```

**Comment by kosso** [comment] 2012-09-03 22:34
I think they will have already started speccing this one out. 

But that aside, my comment would be to have the coordinates separated into latitude and longitude.

**Comment by dquick-freelance** [comment] 2012-09-03 22:35
Agree with @kosso about separating them.  Would also add "altitude" and "accuracy".

Is there already a well-defined spec in one of the mobile ecosystems we could just borrow? At least some of the mobile devs would have it easy that way...

**Comment by jazzychad** [comment] 2012-09-03 22:37
is "geolocation" only specific to a single point? otherwise, the "value" portion needs another "type" identifier such as "Point", "Bounds", "Polygon", "Path", etc... then the "coordinates" would describe that type... other types might need more metadata to fully describe them...

Let us think deeply about the domain-space before plunging ahead.

**Comment by ghost** [comment] 2012-09-03 22:38
Maybe we should also add a 'name' or 'description' field so that a location can be labeled?

**Comment by matthewp** [comment] 2012-09-03 22:40
@jazzychad I saw that Twitter uses "Point" but I couldn't find any other examples.  Makes sense to let net.app.core.geolocation be abstract though. Can you provide an example for Bounds or Polygon?

**Comment by jnovack** [comment] 2012-09-03 22:44
http://dev.w3.org/geo/api/spec-source.html has a good start, defines longitude, latitude, altitude, accuracy.  I like the free-form text field as an alternative, or addition, which means you may want to source field (gps, free-form, etc) which has to follow a MUST BE ONE OF (ieee terminology)

**Comment by ghost** [comment] 2012-09-03 22:44
@jazzychad Maybe just an array of locations? They could be used to create any arbitrary shape.

**Comment by berg** [comment] 2012-09-03 22:45
Thanks for kicking this off, @matthewp. This is the annotation I've personally thought the most about. Thoughts:

There should be a separation between location and place. Let's focus on location only. Place, for lack of a better term, is the "humanized" location information.

My thoughts on location were that we should just put a GeoJSON "Feature" object inside of the annotation. E.g.:

``` js
{ "type": "Feature",
       "geometry": {
         "type": "Polygon",
         "coordinates": [
           [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0],
             [100.0, 1.0], [100.0, 0.0] ]
           ]
       },
       "properties": {
         "prop0": "value0",
         "prop1": {"this": "that"}
         }
       }
```

**Comment by berg** [comment] 2012-09-03 22:46
http://www.geojson.org/geojson-spec.html#feature-objects

**Comment by matthewp** [comment] 2012-09-03 22:48
Thanks @berg, can you tldr this for us a little bit?  What is the purpose of "type": "Feature"?  Purpose of properties?

**Comment by matthewp** [comment] 2012-09-03 22:52
The wiki page has a bit more information. http://wiki.geojson.org/GeoJSON_draft_version_6  If this is a thorough spec (and it seems to be), then I definitely think it's the way to go.

**Comment by berg** [comment] 2012-09-03 22:58
It is a pretty thorough spec, but it might be overkill. Either way, if we're merely going to allow for coordinates, I think that merely using the GeoJSON coordinate format might be the way to go.

We can use properties for altitude, accuracy, location source, etc.

**Comment by stereoket** [comment] 2012-09-03 22:58
Would that then be capable of parsing `FeatureCollections` .. the structure would then alter slightly, how would clients deal with that, unless you adapted the annotation format for ADN? I think you can still use geoJSON, but it might need slight adaptation for use cases. Depends on how the geo aspect could be used.

**Comment by stereoket** [comment] 2012-09-03 23:00
i think the annotation type should be `geo` and allow for `point` & `polygon` data - as they are by far the most popular. Having the ability to use some placeID - could be useful, but there are so many systems. 

There, perhaps, should be a way of choosing which place provider you wanted to use, to retrieve the relevant bounding box (polygon) or point data.

**Comment by berg** [comment] 2012-09-03 23:01
Not sure we need FeatureCollections. I think single feature per annotation is OK.

**Comment by matthewp** [comment] 2012-09-03 23:04
@stereoket I think including places might be overkill. I'd prefer if we moved specs for the individual place services into their own namespaces outside of net.app.core.*

**Comment by matthewp** [comment] 2012-09-03 23:07
FWIW Twitter only uses the "geometry" portion of the spec.  https://dev.twitter.com/docs/api/1/get/statuses/show/%3Aid

**Comment by stereoket** [comment] 2012-09-03 23:16
@berg sure, i was just remarking on the use of geoJSON, and dropping it in, in its existing format. Which i agree is a little overkill. 

@matthewp it may well be overkill. I just see an opportunity to create a format that allows its inclusion and choice of place provider.

Of course I could just use my own annotation to perform this.

**Comment by swhitley** [comment] 2012-09-03 23:16
A lot of work went into the microformat specs.  I would hope that we could leverage all of that thought and at least use those schemas as a starting point.

http://microformats.org/wiki/geo

**Comment by berg** [comment] 2012-09-03 23:21
@swhitley the geo microformat seems specific to HTML/XML. Not sure if that would be the best choice. I think GeoJSON has had nearly as much thought put into it.

**Comment by kosso** [comment] 2012-09-03 23:43
Agreed about this.

Many people might prefer to place themselves in a 'geo-fence' polygon
rather than an exact point.

Kosso

**Comment by swhitley** [comment] 2012-09-04 02:00
@berg I would say that the HTML/XML specifics are just on the surface.  The naming conventions and data structures should be fairly universal.  I just wouldn't want to see us start from scratch on these basic schemas (media, vcard, etc.).  Other bodies spent months hashing out what to include and how to represent the data.

**Comment by berg** [comment] 2012-09-04 02:17
@swhitley I don't think anyone's proposing that we start from scratch on the geo annotation. Have you looked at GeoJSON as proposed above? Seems like it is a better match for this than -- and equally well thought out as -- the microformat you are proposing. Are there any specific reasons why GeoJSON as the proposed solution doesn't work?

**Comment by swhitley** [comment] 2012-09-04 05:34
@berg I apologize for thinking outside the thread.  I was speaking more in terms of the overall effort.  For geo only, I reviewed the GeoJSON spec.  It's flexible, which is good, but I agree that it seems like overkill.  I wish they had clearly defined latitude and longitude.  The coordinates could easily be misread.

I'd say that we're better off going with a simpler format for geo.  @matthewp's start, modified based on the spec from @jnovack would be easier to implement and comprehend.  I do think that GeoJSON could be brought in under a different namespace later for more complex geometry.

**Comment by matthewp** [comment] 2012-09-04 15:19
@swhitley  I do think limiting it to just a Point would be a mistake though. I say we use GeoJSON but limit it only to the "Feature" type, so that you wind up with something like this:

``` json
{
  "type": "net.app.core.geolocation",
  "value": {
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0],
        [100.0, 1.0], [100.0, 0.0] ]
      ]
    },
    "properties": {
      "altitude": 4400
    }
  }
}
```

This allows us to have any number of geometrics, and allows us to attach additional properties.  Outside the scope would be things like human understandable places.  I think that should go in a separate namespace.

**Comment by swhitley** [comment] 2012-09-04 19:09
@matthewp - I find "geometry," "Polygon," and the unlabeled sets of coordinates confusing.  In most cases, I only want a quick way to identify lat and lng.  The GeoJSON spec is good if you'll be doing a lot of other work related to geometrical shapes, but I wouldn't expect that level of detail in a basic geo schema.

I'd counter with something like this:

```
{
    "type": "net.app.core.geolocation",
    "value": {
    "coordinates": {
        "latitude": 37.441,
        "longitude": -122.141
    },
        "properties": {
        "altitude": 4400
        }
}
```

My example is based on your work and the following specs.

http://dev.w3.org/geo/api/spec-source.html
http://www.w3.org/2003/01/geo/

**Comment by beccadax** [comment] 2012-09-05 05:43
I think we're losing sight of our goals here. Specifying arbitrary shapes may sometimes be useful, but I don't think it's the common case.

I think we should look to the principle of graceful degradation here. That means designing a format that has sufficient expressive power for complex cases, but that doesn't require clients to interpret the full format in order to extract something useful.

The common case of a location annotation is a single point on Earth. So we should support something basic as the default:

```
{
     "latitude": 33.699154,
     "longitude": -118.004537
}
```

And allow for some more complicated things if you want them, like altitude (in meters):

```
{
     "latitude": 33.699154,
     "longitude": -118.004537,
     "altitude": 9
}
```

Or accuracy (in meters):

```
{
     "latitude": 33.699154,
     "longitude": -118.004537,
     "altitude": 9,
     "accuracy": 500
}
```

Or a place name:

```
{
     "latitude": 33.699154,
     "longitude": -118.004537,
     "altitude": 9,
     "accuracy": 500,
     "name": "Huntington Central Park"
}
```

Or polygons (expressed as degree offsets from the latitude and longitude):

```
{
     "latitude": 33.699154,
     "longitude": -118.004537,
     "altitude": 9,
     "accuracy": 500,
     "name": "Huntington Central Park",
     "boundaries": [ [ -0.05, -0.05], [0, 0.05], [0.05, -0.05] ]
}
```

Or, for when we get NASA on App.net:

```
{
    "latitude": -4.5895,
    "longitude": 137.4417,
    "altitude": -4,451,
    "name": "Gale Crater",
    "accuracy": 2400,
    "astronomical_body": "Mars"
}
```

But a client need understand nothing more complicated than latitude and longitude to usefully display a location annotation.

**Comment by berg** [comment] 2012-09-05 06:10
Hmm. I've actually come around on this a bit. I think that what @brentdax is proposing sounds reasonable. The primary argument for using GeoJSON is to be able to specify polygons – for users who are unwilling to share an exact location. If we leave the sharing of inexact location to a places database (to which that application is more suited IMHO), we can narrow the scope of this to a specific point, so that would be OK.

**Comment by swhitley** [comment] 2012-09-05 06:39
I support @brentdax's proposal as well.  It's simple and clear.

**Comment by matthewp** [comment] 2012-09-05 12:05
@swhitley @brentdax GeoJSON supports Point as well, I just copy and pasted an example I had found which happened to be Polygon. Here's a point:

``` json
{
  "type": "net.app.core.geolocation",
  "value": {
    "geometry": {
      "type": "Point",
      "coordinates": [40.7142,74.0064]
    },
    "properties": {
      "altitude": 4400
    }
  }
}
```

I think reinventing the wheel here is a really bad idea. You're going to run into scenarios that you haven't thought about (but others have, hence existing standards). And you're going to make it harder for API consumers to parse.  The flat proposal of @brentdax is going to require a lot of conditionals, whereas GeoJSON is a simple switch on type.

**Comment by swhitley** [comment] 2012-09-05 16:34
@matthewp - I found so many different geo standards that I gave up searching.

Property names aside, I still have a major issue with GeoJSON and the unlabeled collection of coordinates (and that they're reversed according to the popular lat/long order).  

If the following items are all optional, could we compromise with a combination of the two approaches?

This leaves us with both a simple schema and a more complex schema.  Applications will know which properties they need to use and will normally pre-select the correct messages.  The if/then for the existence of the property would be cursory.

So, below, I'm proposing "net.app.core.geojson" as its own namespace.  I'm also proposing that we allow parent/child relationships in the _annotations_ array.

``` json
    {
        "type": "net.app.core.geolocation",
        "value": {
            "latitude": 74.0064,
            "longitude": 40.7142,
            "altitude": 4400,
            "annotations": [{
                "type": "net.app.core.geojson",
                "value": {
                        "geometry": {
                            "type": "Point",
                            "coordinates": [40.7142,74.0064]
                        },
                        "properties": {
                            "altitude": 4400
                    }
                }
            }]
        }
    }
```

**Comment by berg** [comment] 2012-09-05 18:02
@swhitley I do not think it is worthwhile to include both types of information in the annotation.

@matthewp Given that the amount of information in the Point geometry type is relatively small, and given that the primary reason of using more complex geometry types is to intentionally decrease the accuracy of the shared location, I think we can safely encapsulate the other cases in a places database -- saying that you are in San Francisco, CA or SOMA, San Francisco, CA or Cento Cafe, SOMA, San Francisco, CA can all be handled this way. I've implemented geolocation features -- both the client side and server side -- several times before, and there wasn't much value derived from using GeoJSON. I think that we should err on the side of simplicity and developer happiness here and use the proposal from @brentdax.

I know that I would prefer to consume a simpler format than GeoJSON.

**Comment by berg** [comment] 2012-09-05 18:04
Actually, let me refine that a bit: let's _only_ include the point/altitude/accuracy bits, exclude name, and in the short term, only support omitting `astronomical_body` thus implying Earth ;)

**Comment by swhitley** [comment] 2012-09-05 18:15
@berg I agree, but I also wanted to introduce the idea of nested annotations.  Perhaps we can discuss this on another thread.

**Comment by beccadax** [comment] 2012-09-06 01:07
@matthewp I think it's absolute madness to require people to use a complicated format with a 2,400-word specification that was designed for very different use cases. The geolocation annotation does not exist to arbitrarily scribble on a map; it exists to specify the geographic source of a post. If you want to arbitrarily scribble on a map, that's a different semantic meaning and should be done in a different type of annotation.

There are a few different things I can see you actually doing with a post geolocation:
1. Displaying a post's location to a user.
2. Ordering or filtering posts by proximity to a location.
3. Classifying posts into different regions and then calculating statistics for the regions (e.g. regional trending topics).

Whatever format we choose should make these sorts of tasks easy to implement. All of them essentially require a point, so we should make sure there's _one_ way to derive a point from a geolocation annotation, not two or three or seven depending on which geometry the user's client decides to annotate the post with.

Having said that, @berg, @swhitley, and @matthewp, I see no reason we shouldn't specify a format for other geometries, as long as clients that don't care about them can safely ignore them. It seems like it'd be better to specify one format now than deal with multiple incompatible formats later. This could be GeoJSON embedded in a "geometry" field if you'd like, but I'd personally prefer that it be relative to the geolocation's latitude and longitude, because I think that would reduce the chance of specifying a shape that doesn't include the point specified in the annotation.

@swhitley, I'm not sure what a "nested" annotation would gain us over embedding its value directly. This really should be a separate discussion.

@berg and generally: I really think we should have only one annotation indicating the location the post was made from. That means we should incorporate "place" into the geolocation annotation. I must admit that I don't know very much about place lookup, so this may be a bit naïve, but I think that the posting client ought to boil the place down to coordinates and a name for the benefit of other clients which may not be using the same (or any) location lookup system. We can add additional fields for place identifiers in whatever formats are appropriate, but I think that clients which only understand the coordinates ought to be able to display the geolocation of posts annotated with a place.

And `astronomical_body` is sort of a joke, but it seems like if Elon Musk gets his way, it may become useful sooner than we think...

**Comment by berg** [comment] 2012-09-06 01:31
@brentdax Annotations are designed to be complimentary, and in order to specify location information users should not be forced to share their precise location. Association with a place is useful separately from adding precise geographic information.

In order for this annotation to be widely supported, I again think we should err on the side of simplicity rather than complexity.

Therefore, I propose:

``` js

    {
        "type": "net.app.core.geolocation",
        "value": {
            "latitude": 74.0064,
            "longitude": 40.7142,
            "altitude": 4400,
            "horizontal_accuracy": 100,
            "vertical_accuracy": 100
        }
    }
```

**Comment by beccadax** [comment] 2012-09-06 01:37
@berg I certainly agree that you should not have to share your precise location. If you are sharing a place, I would expect your geolocation attribute's latitude and longitude to be the location of that place, not your device. Hence, if all you want to share is that you're in San Francisco, the latitude, longitude, accuracy, and (if provided) geometry/boundaries would be those of San Francisco, not your exact location.

**Comment by berg** [comment] 2012-09-06 01:43
@brentdax OK, we agree on that. I think I'd like to find a good way to make this easy for clients, rather than having to have them understand the complexities of geo data, which is why just specifying a place ID is possibly the easiest way to go.

**Comment by berg** [comment] 2012-09-06 01:46
Possibly we (App.net) could expose a properly formatted geolocation annotation with each place (as we'll presumably have a place database to search — more on this soon ;)). I just don't want to deal with the overhead of massive JSON blobs of MultiPolygon crap just to say "Hey, I posted this from San Francisco!" That seems wasteful.

**Comment by dquick-freelance** [comment] 2012-09-06 01:49
Bryan, in your example, is altitude in meters? Feet? Nautical miles? ;-)

**Comment by berg** [comment] 2012-09-06 01:51
@dquick-freelance [smoots](http://en.wikipedia.org/wiki/Smoot), of course.

More seriously: meters. :) Definitely meters.

**Comment by beccadax** [comment] 2012-09-06 01:59
@berg I would be thrilled if I could submit something like this to App.net:

```
{
    "latitude": 37.771071,
    "longitude": -122.412736,
    "place_precision": "city"
}
```

And App.net would magically translate that to:

```
{
    "latitude": 37.771071,
    "longitude": -122.412736,
    "name": "San Francisco, CA",
    "altitude": 16,
    "horizontal_accuracy": 12000,
    "vertical_accuracy": 300,
    "place_id": "1234567890"
}
```

(I believe those accuracy numbers create a cylinder that will enclose the entire city; if I'm mistaken, substitute correct numbers.)

This could be either something that happens when I create a post, or a separate API call made beforehand. If it were a separate API call, it could return a list of relevant places, and the user could choose one with an appropriate level of precision. Then my app could drop that into my post's annotation set and we could all be on our merry way.

**Comment by jazzychad** [comment] 2012-09-06 02:22
Maybe we can punt on the larger discussion of what to do with all possible geolocation shapes until later if we decide that we just want to focus on Points for now. This is obviously the most common thing that clients will want to implement... 

So how about we just create the **net.app.core.geolocation.point** annotation name

``` javascript
{
        "type": "net.app.core.geolocation.point",
        "value": {
            "latitude": 74.0064,
            "longitude": 40.7142,
            "altitude": 4400,
            "horizontal_accuracy": 100,
            "vertical_accuracy": 100
        }
    }
```

personally, I would opt for "lat" and "lng" as the value identifiers to save bytes.

altitude, horizontal_accuracy, and vertical_accuracy are optional. latitude and longitude are required.

**Comment by swhitley** [comment] 2012-09-06 02:25
I agree with the simple view being presented and that Latitude and Longitude would be the only required properties.  That will probably take care of 90% of the use cases.

**Comment by dquick-freelance** [comment] 2012-09-06 02:30
+1 to Chad's proposal in toto

**Comment by beccadax** [comment] 2012-09-06 02:46
@jazzychad I don't agree with using "point" in the identifier; there is no semantic difference between a point annotation and an area annotation, and I very much believe that any geometry we add should be done in a way that's compatible with naïve clients that only understand points. We don't have to decide how that geometry will be expressed at this time, just that it'll be done by adding new fields to the `net.app.core.geolocation` annotation, and so clients should ignore any fields they don't recognize.

I also think we should use full-length names. Clarity is more important than saving eleven bytes of an 8K size limit.

Finally, we may have to add a field or two for places, but it sounds like @berg will be able to tell us more on that front in the next few days...

**Comment by jazzychad** [comment] 2012-09-06 02:58
@brentdax well, what I would really rather do is this:

``` javascript
    {
        "type": "net.app.core.geolocation",
        "value": {
            "type": "Point",
            "coordinates": [[123.45, 32.05]]
        }
    }
```

that way we can have arbitrary points, lines, polygons in one type of annotation (and also remove the lat/lng discussion), but I'm afraid this will be an unpopular proposal.

In fact, the "Point" type hint is redundant since there is only 1 pair of coordinates in the coordinate array. The type of point/line/polygon being described can be inferred from the length of that array.

Either way, I really **seriously** care about saving bytes as things move more toward mobile consumption. 3G connections still suck wind speed-wise, and every byte saved helps, especially with gzip compression over the wire. So I will staunchly defend that choice. lat/lng are equally clear when discussing the domain of geolocation.

I typically try to stay out of groupthink discussions, but I was asked to chime in. So, I've said my piece. Now, I'm going to go build cool stuff while this discussion drags on.

**Comment by berg** [comment] 2012-09-06 03:07
I agree with @brentdax re: the point suffix, and I disagree w/ @jazzychad on the short keys -- lat/lng are fine, but when you get into alt, hacc, vacc, etc., it gets a little crazy. I'd prefer descriptive keys over saving a few bytes.

This thread is a bit long in the tooth, I'm afraid, and I certainly haven't done much to make things better. So I'm going to close this issue and make the preliminary geo annotation look like:

``` js
{
    "type": "net.app.core.geolocation",
    "value": {
        "latitude": 74.0064,
        "longitude": 40.7142,
        "altitude": 4400,
        "horizontal_accuracy": 100,
        "vertical_accuracy": 100
    }
}
```

**Closed as completed** 2012-09-06 03:07 UTC

**Comment by beccadax** [comment] 2012-09-06 03:09
@berg, your example there still includes the `point` suffix. Did you intend to drop it?

**Comment by berg** [comment] 2012-09-06 03:13
@brentdax yes I did. Edited my previous post. :)

**Comment by tonymillion** [comment] 2012-09-06 18:58
SANITY PREVAILED!!!!! @berg thanks ;)

**Comment by kosso** [comment] 2012-09-09 23:38
at last! :) cheers!

**Comment by mthurman** [comment] 2012-09-11 05:10
Just to follow up, this spec has been published: https://github.com/appdotnet/api-spec/blob/master/annotations.md#geolocation
