### ISSUE TITLE
Optionally use GET parameter instead of fragment for desktop auth flow

### ISSUE THREAD

**Issue by liGhun** [appdotnet/api-spec#264] opened 2012-12-26 18:30 UTC
Fragments in URLs are quite disturbing when used in different browsers together with redirects. In consequence it is very hard to implement the desktop auth flow within the standard Windows browser (IE < 10) which is the case in all desktop Windows apps using the build in browser of Windows (except Windows 8).

The problem is that the fragment gets lost and you can't see it in the URL but only if you have the full headers/content.

My wish: optionally deliever the #access_token=xxx as ?access_token=xxx  which are standard GET paremeters which can be parsed easily and everywhere.

Some more info about the redirect / fragment issues: http://stackoverflow.com/questions/2286402/url-fragment-and-302-redirects and http://blogs.msdn.com/b/ieinternals/archive/2011/05/17/url-fragments-and-redirects-anchor-hash-missing.aspx

**Comment by swhitley** [comment] 2012-12-27 05:26
@liGhun Thanks for including the references on this issue.  It explains the problems that I've had with IE in a couple of my solutions.  I hadn't had time to figure it out.

**Comment by liGhun** [comment] 2012-12-27 13:32
I even have found a workaround now:

First: don't use the WPF WebBrowser but instead the Windows Forms one - see http://stackoverflow.com/questions/6487261/wpf-webbrowser-detecting-redirects

Second: Make sure no additional redirects will take place on the redirect URL (most common: http://www.example.com/someFolder without the trailing slash - so use http://www.example.com/someFolder/ instead)

**Comment by berg** [comment] 2012-12-28 19:16
This is by design, actually, as part of the fundamental security assumptions made by OAuth 2. I won't go into detail about why here, but the short version is that is remote servers are untrusted (thus in order to turn a code into a token the client secret is required) and it's assumed that the user trusts the browser, as they're already running it (which is why tokens are only sent in fragments.)

So I'm going to close this issue. I'm glad you found a workaround that works for you.

**Closed as completed by berg** 2012-12-28 19:16 UTC
Labels: needs review
